services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8222:8222"
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/mydb
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    networks:
      - app-network
    environment:
      - VITE_BACKEND_URL=http://backend:8222

networks:
  app-network:
    driver: bridge