services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  backend:
    build: ./backend
    ports:
      - "2011:2011"
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/mydb