services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8222:8222"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://db:27017/guofsyrians_db
      - ENV=development
      - UVICORN_ARGS=--reload
    volumes:
      - ./backend:/app
    working_dir: /app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    command: npm run dev -- --host 0.0.0.0 --port 5173
    networks:
      - app-network

networks:
  app-network:
    driver: bridge