services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8222:8222"
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/mydb
      - ENV=development
      - UVICORN_ARGS=--reload
    volumes:
      - ./backend:/app
    working_dir: /app
<<<<<<< HEAD
    command: sh -c "cd /app && python wait-for-mongo.py && python create_admin.py && python populate_dummy_members.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
=======
    command: sh -c "cd /app && sleep 10 && python create_admin.py && python populate_dummy_members.py && uvicorn main:app --host 0.0.0.0 --port 8222 --reload"
>>>>>>> c52033dfc3955a0177929ddc021e170c0e9b144a
    networks:
      - app-network
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    command: npm run dev -- --host 0.0.0.0 --port 5173
    networks:
      - app-network

networks:
  app-network:
    driver: bridge